// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANhuk01DCYaHy4dZjQYSttujO_F_ZaJzI',
    appId: '1:208416790447:web:f849dc1c85b373952a415a',
    messagingSenderId: '208416790447',
    projectId: 'spotify-app-d67b1',
    authDomain: 'spotify-app-d67b1.firebaseapp.com',
    storageBucket: 'spotify-app-d67b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANhuk01DCYaHy4dZjQYSttujO_F_ZaJzI',
    appId: '1:208416790447:android:57d4fc848fc97aa32a415a',
    messagingSenderId: '208416790447',
    projectId: 'spotify-app-d67b1',
    storageBucket: 'spotify-app-d67b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANhuk01DCYaHy4dZjQYSttujO_F_ZaJzI',
    appId: '1:208416790447:ios:f2af16e4bb80eca32a415a',
    messagingSenderId: '208416790447',
    projectId: 'spotify-app-d67b1',
    storageBucket: 'spotify-app-d67b1.firebasestorage.app',
    iosBundleId: 'com.example.shopDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANhuk01DCYaHy4dZjQYSttujO_F_ZaJzI',
    appId: '1:208416790447:ios:f2af16e4bb80eca32a415a',
    messagingSenderId: '208416790447',
    projectId: 'spotify-app-d67b1',
    storageBucket: 'spotify-app-d67b1.firebasestorage.app',
    iosBundleId: 'com.example.shopDemo.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANhuk01DCYaHy4dZjQYSttujO_F_ZaJzI',
    appId: '1:208416790447:web:e4c62e50aef19e972a415a',
    messagingSenderId: '208416790447',
    projectId: 'spotify-app-d67b1',
    authDomain: 'spotify-app-d67b1.firebaseapp.com',
    storageBucket: 'spotify-app-d67b1.firebasestorage.app',
  );
}
